build:
  stage: build
  image: fedora:29
  before_script:
  - dnf install fpc -y
  script:
  - mkdir binaries
  - fpc -Miso writeToFile.pas
  - mv writeToFile binaries/
  artifacts:
    paths: 
    - binaries
 
test_script:
  image: oyvindg/gitlab-ci-library:xmldev
  dependencies: 
  - build
  stage: test
  script:
  - ant -lib $SAXON_HOME/Saxon9HE.jar
  - ls -ahl result
  - tail -n30 result/*
